name: Build and Push Docker Images

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPOSITORY: docker-repository
  REGISTRY: us-central1-docker.pkg.dev

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-api, users-api, todos-api, log-message-processor, frontend]
    
    steps:
      - uses: actions/checkout@v4

      - name: Auth Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build and Push
        run: |
          IMAGE_LATEST=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ matrix.service }}:latest
          IMAGE_SHA=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ matrix.service }}:${{ github.sha }}
          docker build -t $IMAGE_LATEST -t $IMAGE_SHA ./${{ matrix.service }}
          docker push $IMAGE_LATEST
          docker push $IMAGE_SHA
          echo "✅ Pushed: $IMAGE_LATEST"
          echo "✅ Pushed: $IMAGE_SHA"

      - name: Update Kubernetes manifests
        run: |
          IMAGE_URL=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ matrix.service }}:${{ github.sha }}
          sed -i "s|\${IMAGE_URL}|$IMAGE_URL|g" k8s/applications/${{ matrix.service }}.yaml
          echo "✅ Updated k8s/applications/${{ matrix.service }}.yaml with image: ${IMAGE_URL}"
